Tickets/sitcom 1234
lsst-sitcom/notebooks_vandv pull request #112
Opened 2024-02-21 16:44 UTC by boutigny

I think that I have implemented all the changes requested in SITCOM-1234

2024-02-22 13:36 UTC, b1quint requested changes
I added a few comments, see above. Hopefully this  will now make the comments show up?

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
Hi, @boutigny - could you rename this file to something like `sitcomtn095.py` to match the other two files in the same folder?

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +        tolerance for IMS value to be within requirement. We will apply it to the RMS and bias of the value, with respect to the value at reference_t + post_delta_t
We usually want docstring lines to be shorter than 80 characters. May I ask you to fix that? I was hoping Black would handle it.

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    iT0 = np.argmin(
Do we know what `iT0` means? If so, could we have a more intuitive name for it to improve code readability?

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +        if (krms == []) and (
I would add an empty line between `if` statements. This gives the code some "air" and lets the eyes know when the code is "slightly changing the subject." Kind of a weak visual clue.

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    df_ims,  # input data frame
Let's remove these comments from the argument definition. Any comment here should be, instead, a documentation inside the docstring.

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    imsColumn="xPosition",  # IMS column
We have a mix of `snake_case` and `semiCamelCase` variables. Could you have them all being `snake_case`?

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    f="SITCOM_1172.log",
Can we rename this argument/variable to something more self-explanatory? Maybe `log_file`?

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +        tolerance for IMS value to be within requirement. We will apply it to the RMS and bias of the value, with respect to the value at reference_t + post_delta_t
Same thing here. We would like to have docstrings limited to 80 chars length max.

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    T0 = pd.to_datetime(referenceTime)  # this is slew stop
I suggest replacing `T0` with `slew_stop_t`. Then the variable name becomes more self-explanatory.

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    TZoom = [T0 - delta_window[0], T0 + delta_window[1]]
Following the suggestion above, this one would be `zoom_t`. Or `t_zoom` if you prefer to have the `t` as a prefix. As long as the time variables have some sort of consistency to help readers quickly identify them as timestamps.

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    targetVariablePlot = df_ims[imsColumn][TZoom[0] : TZoom[1]]
We should remove the spaces between `:`. See [this sections of PEP8 for more examples](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements).

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +def compute_settle_time(
This function is much easier to read than the function above, thanks to the empty lines it has in the middle of the code. If would be great if we could have the same blank lines in the rest of the code for both consistency and to improve readability.

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    if len(stabilityCheck[stabilityCheck == True]) <= rollingCheck:  ## == 0:
I would add a space before this `if`.

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    settleInterval = -1
And another space before this line.

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +def get_slew_times(events, i_slew):
This function needs a docstring.

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +def get_IMS_data(events, i_slew, postPadding):
This one needs a docstring too.

2024-02-22 13:36 UTC, b1quint commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    for i in range(len(blockEvents)):
This for loop could benefit from some empty lines within it to help "group" lines that are closely related.

2024-02-22 14:27 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
Done

2024-02-22 14:27 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +        tolerance for IMS value to be within requirement. We will apply it to the RMS and bias of the value, with respect to the value at reference_t + post_delta_t
Done

2024-02-22 14:28 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +        if (krms == []) and (
done

2024-02-22 14:29 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    iT0 = np.argmin(
renamed to something more explicit

2024-02-22 14:31 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    if len(stabilityCheck[stabilityCheck == True]) <= rollingCheck:  ## == 0:
done

2024-02-22 14:31 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    settleInterval = -1
Also removed the 2 commented lines

2024-02-22 14:48 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +def get_slew_times(events, i_slew):
done

2024-02-22 14:48 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +def get_IMS_data(events, i_slew, postPadding):
done

2024-02-22 14:50 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    for i in range(len(blockEvents)):
done

2024-02-22 14:53 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    df_ims,  # input data frame
removed

2024-02-22 14:54 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    imsColumn="xPosition",  # IMS column
I think that I have now converted all (most) of them

2024-02-22 15:22 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    f="SITCOM_1172.log",
renamed

2024-02-22 15:30 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    T0 = pd.to_datetime(referenceTime)  # this is slew stop
done

2024-02-22 15:32 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +    TZoom = [T0 - delta_window[0], T0 + delta_window[1]]
done

2024-02-22 15:36 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +def compute_settle_time(
ok, I tried to add some extra blank lines to improve code readibility

2024-02-22 15:36 UTC, boutigny commented on python/lsst/sitcom/vandv/m1m3/SITCOMTN-095_settling_time_block_analysis.py
> +        tolerance for IMS value to be within requirement. We will apply it to the RMS and bias of the value, with respect to the value at reference_t + post_delta_t
I think it is ok everywhere now

2024-02-23 00:56 UTC, b1quint approved these changes
This looks better now. Thank you very much!

2024-02-23 11:10 UTC, merged