Tickets/sitcom 1223
lsst-sitcom/notebooks_vandv pull request #124
Opened 2024-03-20 16:15 UTC by ltoribiosc

2024-04-03 14:27 UTC, bstalder requested changes
please remove the 1136 file changes.  also clear outputs to the 1223 notebook.  also inline plots are preferred instead of file outputs.

2024-04-03 15:02 UTC, ltoribiosc commented
Thanks Brian. I just deleted the notebook outputs and deleted the 1136 files.

2024-04-12 18:27 UTC, bstalder commented
think you need further commits.  I still see the M1M3 notebook with changes.

2024-04-22 14:41 UTC, ltoribiosc commented
I think you need more commits. I still see the M1M3 notebook with changes.


Where do you see the M1M3 notebook changes? I deleted all the files that were copied from the previous ticket. You should see nothing now. 

I now see 13 commits all related to SITCOM-1223. That is, from this ticket

2024-04-22 15:46 UTC, bstalder commented
I still see it under "file changes"

2024-04-24 09:28 UTC, ltoribiosc reviewed
SITCOM-1136 changes have been reviewed. This file was introduced due to an error when creating the branches. The SITCOM-1223 branch was not created from develop branch but from SITCOM-1136 by mistake. Therefore, in order to merge them it was necessary to copy the last files of SITCOM-1136 here

2024-04-24 09:28 UTC, ltoribiosc commented on notebooks/tel_and_site/subsys_req_ver/m1m3/SITCOM-1136_M1M3_analysis_stability_tracking.ipynb
This file was introduced due to an error when creating the branches. The SITCOM-1223 branch was not created from develop branch but from SITCOM-1136 by mistake. Therefore, in order to merge them it was necessary to copy the last files of SITCOM-1136 here

2024-04-24 09:32 UTC, ltoribiosc commented
<p>Hi Brian. I didn't understand what you were saying. But I think it's fixed now. Tell me if this is the case or if I should do something else. Thank you very much for your help.</p>

2024-04-24 13:59 UTC, bstalder approved these changes

2024-10-22 09:33 UTC, merged