Lsst sitcom/tickets/sitcom 314
lsst-sitcom/notebooks_vandv pull request #2
Opened 2022-05-17 16:54 UTC by isotuela

Please review this PR (Added timestamp for MTAOS plots) Ready for Wednesday 18th execution.

2022-05-17 17:09 UTC, b1quint commented
In general, we are good but, before we merge, please, see the comments above.
For the future, consider also removing the plots from the commits. 
We can leave these ones for now, but we want to avoid filling up the repository with plots.

2022-05-17 19:32 UTC, b1quint requested changes
Please, see the comments above

2022-05-17 19:32 UTC, b1quint commented on notebooks/proj_sys_eng/sitcom_integration/l3_system_integ/LVV-T2190-MTAOS_add_aberrations_plots.ipynb
> +    "aa = np.loadtxt('%s/repos/M2_FEA/data/M2_1um_72_force.txt'%(os.environ[\"HOME\"]))\n",
Please, leave the original path `/notebooks/` instead of `/repost` since `/notebooks/` is the default path for notebooks in everyone's Nublado.

2022-05-17 19:32 UTC, b1quint commented on notebooks/proj_sys_eng/sitcom_integration/l3_system_integ/LVV-T2344-Startup_mt_on_level3.ipynb
> +    "await mtcs.set_state(salobj.State.STANDBY, components=[\"mtptg\"])"
Isn't this supposed to be ENABLED?

2022-05-17 19:32 UTC, b1quint commented on notebooks/proj_sys_eng/sitcom_integration/l3_system_integ/LVV-T2344-Startup_mt_on_level3.ipynb
> +    "await mtcs.set_state(salobj.State.STANDBY, components=[\"mtmount\"])"
Same here, isn't this supposed to be ENABLED?

2022-05-17 19:32 UTC, b1quint commented on notebooks/proj_sys_eng/sitcom_integration/l3_system_integ/LVV-T2344-Startup_mt_on_level3.ipynb
> +    "await mtcs.set_state(salobj.State.STANDBY, components=[\"mtrotator\"])"
Same here, isn't this supposed to be ENABLED?

2022-05-17 19:32 UTC, b1quint commented on notebooks/proj_sys_eng/sitcom_integration/l3_system_integ/LVV-T2344-Startup_mt_on_level3.ipynb
> +    "    overrides = {\"mtm1m3\": 'Default'}\n",
This is good!

2022-05-17 19:32 UTC, b1quint commented on notebooks/proj_sys_eng/sitcom_integration/l3_system_integ/LVV-T2190-MTAOS_add_aberrations.ipynb
> +    "from lsst.ts import utils\n",
Can you move the imports to the top of the notebook, please?

2022-05-17 19:32 UTC, b1quint commented on notebooks/proj_sys_eng/sitcom_integration/l3_system_integ/LVV-T2190-MTAOS_add_aberrations.ipynb
> +    "t.format = \"isot\"\n",
Same here, can you move the imports to the top of the notebook, please?

2022-05-17 19:41 UTC, isotuela commented on notebooks/proj_sys_eng/sitcom_integration/l3_system_integ/LVV-T2190-MTAOS_add_aberrations_plots.ipynb
> +    "aa = np.loadtxt('%s/repos/M2_FEA/data/M2_1um_72_force.txt'%(os.environ[\"HOME\"]))\n",
Done. Thank you Bruno!

2022-05-17 19:42 UTC, isotuela commented on notebooks/proj_sys_eng/sitcom_integration/l3_system_integ/LVV-T2190-MTAOS_add_aberrations.ipynb
> +    "from lsst.ts import utils\n",
Done! Cheers

2022-05-17 19:42 UTC, isotuela commented on notebooks/proj_sys_eng/sitcom_integration/l3_system_integ/LVV-T2190-MTAOS_add_aberrations.ipynb
> +    "t.format = \"isot\"\n",
Done!

2022-05-17 19:52 UTC, isotuela commented on notebooks/proj_sys_eng/sitcom_integration/l3_system_integ/LVV-T2344-Startup_mt_on_level3.ipynb
> +    "await mtcs.set_state(salobj.State.STANDBY, components=[\"mtptg\"])"
Yep!

2022-05-17 19:52 UTC, isotuela commented on notebooks/proj_sys_eng/sitcom_integration/l3_system_integ/LVV-T2344-Startup_mt_on_level3.ipynb
> +    "await mtcs.set_state(salobj.State.STANDBY, components=[\"mtmount\"])"
Same:)

2022-05-17 19:52 UTC, isotuela commented on notebooks/proj_sys_eng/sitcom_integration/l3_system_integ/LVV-T2344-Startup_mt_on_level3.ipynb
> +    "await mtcs.set_state(salobj.State.STANDBY, components=[\"mtrotator\"])"
Done

2022-05-17 19:53 UTC, isotuela commented
Thank you for your review!

2022-05-18 14:54 UTC, b1quint approved these changes
All the changes are good now. Thank you very much!

2022-05-18 15:22 UTC, merged

2022-05-18 15:24 UTC, isotuela commented
Thank you!