latest version tested on BTS with timeout implemented, already review…
lsst-sitcom/notebooks_vandv pull request #83
Opened 2023-11-08 22:19 UTC by gabrirod86

…ed once by Te-Wei

2023-11-08 22:35 UTC, hdrass requested changes
I do not understand how you increase the position:
Please add comments to document how you set the position:
 
start = await asyncio.to_thread(input, 'Start')
    match start:
        case 'y':
            pass
        case _:
            return
            
    position = await asyncio.to_thread(input, 'Position')
    if len(position) == 0:
        return
    position = float(position)    
 
Can you add some comments here?

2023-11-08 22:43 UTC, gabrirod86 commented
Hi Holger,

The position is a user input parameter that is queried from the terminal in
the Jupiter Notebook interface, we add the comment in the script;)
Thanks

Il giorno mer 8 nov 2023 alle ore 19:36 Holger Drass <
***@***.***> ha scritto:

> ***@***.**** requested changes on this pull request.
>
> I do not understand how you increase the position:
> Please add comments to document how you set the position:
>
> start = await asyncio.to_thread(input, 'Start')
> match start:
> case 'y':
> pass
> case _:
> return
>
> position = await asyncio.to_thread(input, 'Position')
> if len(position) == 0:
>     return
> position = float(position)
>
> Can you add some comments here?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lsst-sitcom/notebooks_vandv/pull/83#pullrequestreview-1721392092>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5DCNVIALUQ636YB5YWDUOTYDQCNHAVCNFSM6AAAAAA7DTJ3E6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMRRGM4TEMBZGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-13 16:50 UTC, hdrass approved these changes

2023-11-13 16:50 UTC, hdrass commented
Looks good. I now understand the code better. Thanks.

2023-11-13 16:50 UTC, merged